Add ability to add new platforms to the product
AlmaLinux/albs-web-server pull request #1008
Opened 2024-10-04 13:54 UTC by maccelf

Resolves: AlmaLinux/build-system#358

2024-10-04 17:14 UTC, anfimovdm requested changes

2024-10-04 17:14 UTC, anfimovdm commented on alws/crud/products.py
> +        items_to_insert.append(repo)
Most logic of the new function repeats the same logic as in the `create_product` function, please move common logic to a separate function and reuse it

2024-10-09 17:49 UTC, anfimovdm approved these changes

2024-10-16 12:02 UTC, soksanichenko reviewed
LGTM, except a tiny comment. It's FYI.

2024-10-16 12:02 UTC, soksanichenko commented on alws/crud/products.py
> +):
add typing for a return value

2024-10-16 16:10 UTC, anfimovdm approved these changes

2024-10-16 16:30 UTC, merged