Add access control to `products/{id}/add_platforms`
AlmaLinux/albs-web-server pull request #1027
Opened 2024-10-21 19:47 UTC by bklvsky

- Add access control
- Black formatting

Resolves: AlmaLinux/build-system#359

2024-10-24 15:48 UTC, anfimovdm approved these changes

2024-11-04 09:16 UTC, maccelf approved these changes

2024-11-04 09:29 UTC, maccelf requested changes
Could you please check what is going on with tests ?

2024-11-04 13:11 UTC, bklvsky commented
> Could you please check what is going on with tests ?

It was an old problem with tests, it's already fixed in master, just needed a rebase

2024-11-04 15:14 UTC, maccelf approved these changes

2024-11-04 15:15 UTC, merged