Add new parameter to platform
AlmaLinux/albs-web-server pull request #1037
Opened 2024-10-23 22:51 UTC by Kwaizer

2024-11-05 09:07 UTC, maccelf requested changes
I believe you need to do a migration
Also, make sure that the bootstrap script adds new field to platforms

2024-11-05 09:13 UTC, Kwaizer commented
> I believe you need to do a migration Also, make sure that the bootstrap script adds new field to platforms
Forgot to add, thanks for pointing out

2024-11-05 10:18 UTC, soksanichenko requested changes
I agree with comment from Maxim. It's the important thing.

2024-11-07 10:48 UTC, maccelf approved these changes

2024-11-08 09:16 UTC, Korulag approved these changes

2024-11-13 08:59 UTC, javihernandez approved these changes

2024-11-13 09:02 UTC, soksanichenko approved these changes

2024-11-13 09:02 UTC, Korulag approved these changes

2024-11-13 09:02 UTC, merged