albs-89 add column priority to repositories
AlmaLinux/albs-web-server pull request #105
Opened 2022-02-08 09:18 UTC by monkrobot

2022-02-09 05:59 UTC, Korulag requested changes

2022-02-09 05:59 UTC, Korulag commented on alws/alembic/versions/bd8531d3bd24_add_column_priority_to_repositories_set_.py
> +    op.add_column('repositories', sa.Column('priority', sa.Boolean(), nullable=True))
Priority field is integer, not boolean

2022-02-09 05:59 UTC, Korulag commented on alws/models.py
> +    priority = sqlalchemy.Column(sqlalchemy.Boolean, default=False,
Should be integer

2022-02-22 09:16 UTC, anfimovdm approved these changes

2022-02-22 09:16 UTC, anfimovdm commented on alws/alembic/versions/7469773f4f79_add_priority_to_repositories.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Below commands doesn't look like auto generated by `alembic`, so u can delete this comment, not critical

2022-02-23 11:05 UTC, Korulag approved these changes

2022-02-23 11:05 UTC, merged