Enable the release of packages built for AlmaLinux-Kitten-10 on the AlmaLinux-10 platform, and the other way around
AlmaLinux/albs-web-server pull request #1058
Opened 2024-11-18 18:09 UTC by soksanichenko

Resolves AlmaLinux/build-system#369:

- For cross-releasing we should include an RPM artifact if the reference platforms of its build task has intersection with the reference platform of base platform which we want to release a build

2024-11-19 16:12 UTC, soksanichenko commented on alws/release_planner.py
> +                # if we don't found repos for debug package, we can try to
Yes. I've fixed only a comment from spellchecker and didn't notice the rest sentence. Thank you, I'll fix it ASAP.

2024-11-20 15:03 UTC, anfimovdm requested changes

2024-11-21 09:08 UTC, maccelf approved these changes

2024-11-29 11:38 UTC, anfimovdm commented
:warning: Please, don't merge that PR before testing on our stagings

2024-12-06 12:28 UTC, merged