Add queue for long-running tasks [ALBS-147]
AlmaLinux/albs-web-server pull request #109
Opened 2022-02-11 09:01 UTC by AvoidMe

* Create new service - task_queue. Which is backed by dramatiq with RabbitMQ broker under the hood.
* Move create_build and build_done endpoints to new task_queue service, this endpoints now only schedules new tasks for dramatiq.

2022-02-11 12:11 UTC, Korulag requested changes

2022-02-11 14:23 UTC, AvoidMe commented on alws/dramatiq/build.py
> +            for linked_id in build_request.linked_builds:
`add_task` is actually not pushing anything in database, `db.flush` doing it in single batch couple lines later

2022-02-14 09:27 UTC, anfimovdm approved these changes

2022-02-14 16:54 UTC, AvoidMe commented on alws/dramatiq/build.py
> +async def _build_done(request: build_node_schema.BuildDone):
Fixed, we can even delete helpers when work for migrating from async to sync sqlalchemy will be finished

2022-02-28 21:13 UTC, merged