Errata migration
AlmaLinux/albs-web-server pull request #114
Opened 2022-02-16 09:51 UTC by AvoidMe

2022-03-01 10:55 UTC, soksanichenko requested changes

2022-03-01 10:55 UTC, soksanichenko commented on updateinfo_mover.py
> +def clean_module_release(release: str) -> str:
Why is it name `clean...`?

2022-03-01 10:55 UTC, soksanichenko commented on updateinfo_mover.py
> +        if is_gzip_file(modules_yaml):
metadata can be compressed using algorithm `xz`

2022-03-01 10:55 UTC, soksanichenko commented on updateinfo_mover.py
> +    def find_metadata(repodata_dir, key) -> str:
Why did you not use module `createrepo_c` for that?

2022-03-01 10:55 UTC, soksanichenko commented on updateinfo_mover.py
> +        for key in (
Move tuple to constant

2022-03-01 11:10 UTC, soksanichenko requested changes

2022-03-01 11:10 UTC, soksanichenko commented on updateinfo_mover.py
> +    def find_metadata(repodata_dir, key) -> str:
```
repomd_object= cr.Repomd(repomd_file_path)
repomd_records = repomd_object.records
```

2022-03-24 15:34 UTC, Korulag approved these changes

2022-03-24 17:26 UTC, merged