Initial release
AlmaLinux/albs-web-server pull request #142
Opened 2022-03-15 16:37 UTC by AvoidMe

2022-03-16 09:36 UTC, Korulag approved these changes

2022-03-17 20:29 UTC, anfimovdm requested changes

2022-03-17 20:29 UTC, anfimovdm commented on alws/crud/release.py
> +        pkg_info['repositories'] = new_repos
it's old logic from my previous changes for noarch checking, pls compare ur branch with actual `master` branch and delete old logic

2022-03-22 07:53 UTC, anfimovdm approved these changes

2022-03-22 07:54 UTC, merged