ALBS-258 Add pageNumber query parameter in GET releases endpoint
AlmaLinux/albs-web-server pull request #170
Opened 2022-04-13 10:02 UTC by monkrobot

2022-04-14 09:54 UTC, anfimovdm requested changes

2022-04-14 09:54 UTC, anfimovdm commented on alws/crud/release.py
> +        return {'builds': release_result.scalars().all(),
it's should be `releases` instead of `builds`

2022-04-14 09:54 UTC, anfimovdm commented on alws/schemas/release_schema.py
> +    builds: typing.List[Release]
same as above

2022-04-14 10:14 UTC, anfimovdm approved these changes

2022-04-14 13:37 UTC, maccelf requested changes

2022-04-14 13:37 UTC, maccelf commented on alws/crud/release.py
> +    ).order_by(models.Release.id)
Add `models.Release.id.desc()` instead `models.Release.id` so that releases are in the correct order

2022-04-15 08:34 UTC, maccelf approved these changes

2022-04-25 11:06 UTC, merged