Add transaction to build done
AlmaLinux/albs-web-server pull request #177
Opened 2022-04-20 07:15 UTC by AvoidMe

2022-04-20 07:54 UTC, Korulag approved these changes

2022-04-20 08:47 UTC, anfimovdm requested changes

2022-04-20 08:47 UTC, anfimovdm commented on alws/crud/build_node.py
> +    sucess = True
typo

2022-04-20 08:47 UTC, anfimovdm commented on alws/crud/build_node.py
> +        sucess = False
same above

2022-04-20 08:47 UTC, anfimovdm commented on alws/crud/build_node.py
> +    return sucess
same above

2022-04-20 09:03 UTC, anfimovdm approved these changes

2022-04-20 11:24 UTC, Korulag approved these changes

2022-04-20 12:43 UTC, soksanichenko approved these changes

2022-04-20 12:43 UTC, soksanichenko commented on alws/constants.py
> +DRAMATIQ_TASK_TIMEOUT = 36000000  # 10 hours in milliseconds
You can just write as `60*60*1000`

2022-04-22 08:20 UTC, Korulag approved these changes

2022-04-22 08:34 UTC, anfimovdm approved these changes

2022-04-22 10:30 UTC, merged