Verify packages signatures during export from Pulp
AlmaLinux/albs-web-server pull request #190
Opened 2022-05-04 10:19 UTC by Korulag

2022-05-04 10:37 UTC, soksanichenko approved these changes

2022-05-04 12:04 UTC, anfimovdm requested changes

2022-05-17 10:33 UTC, soksanichenko commented on scripts/packages_exporter.py
> +            if not link.endswith('/'):
1. You can always add slash to the end of url and it doesn't break anything
2. Use `from urllib.parse import urljoin` for joining uris. As I remember `os.path.join` can return incorrect result in some cases.

2022-05-17 10:33 UTC, soksanichenko commented on scripts/packages_exporter.py
> +                if not os.path.exists(repodata_path):
For what do you check existing the directory if you use `exist_ok=True`?

2022-05-17 10:36 UTC, soksanichenko commented on scripts/packages_exporter.py
> +            if not link.endswith('/'):
Not actual

2022-05-17 10:37 UTC, soksanichenko approved these changes

2022-05-17 10:42 UTC, anfimovdm approved these changes

2022-05-17 10:45 UTC, merged