ALBS-409: Wait for other build tasks before creating test tasks
AlmaLinux/albs-web-server pull request #248
Opened 2022-07-14 13:18 UTC by javihernandez

2022-07-14 13:23 UTC, javihernandez commented
Questions:
* Not sure whether that's the best place to do it - maybe better doing it [here](https://github.com/AlmaLinux/albs-web-server/blob/af9fc0e7f00a9c30f54aa97fd18585f6df4a2a95/alws/dramatiq/build.py#L56-L60)?
* Not sure if it's okay to wait the way we're doing right now
* How about using the `get_db` approach? Can I reuse the session I already get in [here](https://github.com/AlmaLinux/albs-web-server/blob/af9fc0e7f00a9c30f54aa97fd18585f6df4a2a95/alws/crud/test.py#L19)?

2022-07-18 13:57 UTC, anfimovdm approved these changes

2022-07-22 12:23 UTC, Korulag requested changes

2022-07-22 12:23 UTC, Korulag commented on alws/dramatiq/build.py
> +        while not all_completed:
This one will hold function possibly for a very long time. Probably we just need to do one-time check and if not all tasks are completed then just skip creating test tasks

2022-07-25 09:38 UTC, Korulag requested changes

2022-07-25 09:38 UTC, Korulag commented on alws/crud/test.py
> +            select(models.BuildTask.id).where(and_(
`and` is default grouping of conditions in SQLAlchemy, so you can skip it in simple requests

2022-07-25 09:38 UTC, Korulag commented on alws/dramatiq/build.py
> +                models.BuildTask.build_id == build_id,
Same here, no need in `and_` operation

2022-07-25 09:48 UTC, Korulag approved these changes

2022-07-25 17:46 UTC, anfimovdm approved these changes

2022-07-27 13:46 UTC, merged