ALBS-8 add some basic tests for decode_JWT_token and BuildDoneArtifact.is_debuginfo
AlmaLinux/albs-web-server pull request #26
Opened 2021-10-28 07:51 UTC by monkrobot

2021-11-01 08:52 UTC, anfimovdm approved these changes

2021-11-01 10:48 UTC, JohnKepplers approved these changes

2021-11-02 09:18 UTC, soksanichenko requested changes

2021-11-02 09:18 UTC, soksanichenko commented on tests/test_schemas/build_node_schema_test.py
> +        self.assertEqual(True, test_BuildDoneArtifact.is_debuginfo, message)
self.assertTrue

2021-11-02 09:18 UTC, soksanichenko commented on tests/test_schemas/build_node_schema_test.py
> +        self.assertEqual(False, test_BuildDoneArtifact.is_debuginfo, message)
The same as above

2021-11-02 15:23 UTC, Korulag commented on requirements.txt
> -psycopg2-binary==2.9.1
No it's not, we need it for test scheduler

2021-11-02 15:25 UTC, Korulag requested changes

2021-11-02 15:25 UTC, Korulag commented on tests/test_crud/crud_test.py
> +    async def custom_db(self):
Create a base class with this method derived from TestCase, then inherit it for other tests that need database.

2021-11-02 15:46 UTC, AvoidMe commented on requirements.txt
> -psycopg2-binary==2.9.1
It's duplicate, we have psycopg2-binary two times in out requirements.txt:
```
fastapi[all]==0.68.1
uvicorn==0.13.4
asyncpg==0.24.0
psycopg2-binary==2.9.1        # first one
pydantic==1.8.2
SQLAlchemy==1.4.25
aiohttp==3.7.4.post0
PyJWT==2.1.0
alembic==1.7.3
aioredis==2.0.0
psycopg2-binary==2.9.1        # second
jmespath==0.10.0
```

2021-11-02 20:55 UTC, rpisarev reviewed
I guess you should resolve conflicts as well

2021-11-03 08:37 UTC, rpisarev approved these changes

2021-11-03 08:37 UTC, rpisarev approved these changes

2021-11-03 11:00 UTC, soksanichenko approved these changes

2021-11-04 08:55 UTC, merged