ALBS-724 Allow to set rpm macros in build flavours
AlmaLinux/albs-web-server pull request #341
Opened 2022-10-31 10:31 UTC by maccelf

Sometimes we need to set some rpm macros only for beta not affecting stable builds.
It is necessary to implement ability to set rpm macros in flavours.
If platform and flavour have the same macros then flavour macros should overwrite platform one i.e. it has higher priority.

2022-10-31 17:27 UTC, anfimovdm requested changes

2022-10-31 17:27 UTC, anfimovdm commented on alws/crud/platform_flavors.py
> +    db_flavour = await find_flavour_by_name(db, flavour.name)
`find_flavour_by_name` can return None, please add check for this

2022-10-31 17:27 UTC, anfimovdm commented on alws/routers/build_node.py
> +                if flavour.data['mock']['macros']:
we can fall here with `KeyError` if flavour.data doesn't have `macros` key

2022-10-31 17:27 UTC, anfimovdm commented on scripts/manage_flavours.py
> +    parser.add_argument(
we don't use this argument

2022-10-31 17:27 UTC, anfimovdm commented on scripts/manage_flavours.py
> +    parser.add_argument(
same as below

2022-10-31 17:27 UTC, anfimovdm commented on scripts/manage_flavours.py
> +        flavour = await pf_crud.find_flavour_by_name(db, flavour_data["name"])
we get db_flavour twice, here and in `pf_crud.update_flavour`

2022-11-01 10:22 UTC, anfimovdm approved these changes

2022-11-02 12:31 UTC, Korulag approved these changes

2022-11-02 12:44 UTC, merged