ALBS-874: Add Sentry integration to the web server
AlmaLinux/albs-web-server pull request #381
Opened 2022-12-21 16:55 UTC by Korulag

2022-12-22 10:24 UTC, soksanichenko approved these changes

2022-12-22 11:50 UTC, anfimovdm requested changes

2022-12-22 11:50 UTC, anfimovdm commented on alws/app.py
> +import sentry_sdk
Is that working without adding `sentry_sdk` to `reqierements.txt`?

2022-12-23 10:11 UTC, javihernandez approved these changes

2022-12-23 10:15 UTC, anfimovdm approved these changes

2022-12-23 10:16 UTC, maccelf approved these changes

2022-12-23 12:08 UTC, merged