ALBS-919 Decrease Pulp storage size for backup
AlmaLinux/albs-web-server pull request #393
Opened 2023-01-16 06:44 UTC by maccelf

2023-01-16 10:35 UTC, Korulag requested changes

2023-01-16 10:35 UTC, Korulag commented on scripts/remove_unnecessary_versions_of_repositories.py
> +            retain_repo_versions = 3
I suggest to leave 3 versions for all RPM repos. That should leave enough data to be able to track all needed info for SBOM

2023-01-16 10:35 UTC, Korulag commented on scripts/remove_unnecessary_versions_of_repositories.py
> +    # await remove_orphans(pulp_client, logger)
Remove the call (and maybe a function) if it's not used

2023-01-16 11:04 UTC, Korulag approved these changes

2023-01-17 15:42 UTC, javihernandez approved these changes
Apart from the minor comment left, LGTM

2023-01-17 15:42 UTC, javihernandez commented on scripts/remove_unnecessary_versions_of_repositories.py
> +    logger.info("All unnecessery version of repositories is deleted")
"All unnecessary versions of repositories have been deleted"
Also, replace "unnecessery" with "unnecessary", found some of them

2023-01-19 10:48 UTC, soksanichenko approved these changes

2023-01-20 10:17 UTC, merged