ALBS-669 Add a meaningful message error when signing builds
AlmaLinux/albs-web-server pull request #395
Opened 2023-01-17 09:22 UTC by maccelf

Current we got non-useful message about error Dismiss and 500 error in a browser’s console

2023-01-17 09:31 UTC, anfimovdm requested changes

2023-01-17 09:31 UTC, anfimovdm commented on alws/routers/sign_task.py
> +        )
We can define catching exceptions through middleware like we do for products (see `alws/middlewares/products.py`)

2023-01-19 10:58 UTC, soksanichenko approved these changes

2023-01-20 10:27 UTC, anfimovdm approved these changes

2023-01-20 10:28 UTC, anfimovdm commented
JFYI, you can use constants from `fastapi.status` for HTTP status codes

2023-01-20 10:29 UTC, merged