ALBS-994 Make "Release Feed" public
AlmaLinux/albs-web-server pull request #452
Opened 2023-03-02 07:38 UTC by maccelf

2023-03-02 07:46 UTC, palyla approved these changes

2023-03-02 09:42 UTC, anfimovdm requested changes
please create a test to check that endpoints works without authorization

2023-03-02 17:09 UTC, anfimovdm requested changes

2023-03-03 11:51 UTC, anfimovdm approved these changes

2023-03-03 11:55 UTC, merged