ALBS-5: Added ability to sign packages
AlmaLinux/albs-web-server pull request #50
Opened 2021-12-06 09:08 UTC by Korulag

This commit brings functionality to sign packages. This includes
database structure, tasks scheduling and changing statuses.

2021-12-06 12:10 UTC, anfimovdm requested changes

2021-12-06 12:10 UTC, anfimovdm commented on alws/crud/release.py
> +    oracle_response = await BeholderClient(settings.packages_oracle_host).post(
Right now in `alws.config` we have vars for oracle and beholder, doesn't they equal?

2021-12-07 10:42 UTC, soksanichenko approved these changes

2021-12-09 08:45 UTC, rpisarev approved these changes

2021-12-13 09:44 UTC, Korulag commented on alws/crud/build.py
> +        #     query = query.filter(models.Build.signed == search_params.signed)
Fixed

2021-12-13 09:49 UTC, anfimovdm approved these changes

2021-12-13 11:38 UTC, merged