ALBS-1044: Add build flavor repos when scheduling test tasks
AlmaLinux/albs-web-server pull request #502
Opened 2023-04-03 14:57 UTC by javihernandez

2023-04-04 08:38 UTC, soksanichenko approved these changes

2023-04-04 08:47 UTC, maccelf approved these changes

2023-04-04 10:31 UTC, anfimovdm requested changes

2023-04-04 10:31 UTC, anfimovdm commented on alws/test_scheduler.py
> +    def __get_repos_for_test_task(task: models.TestTask):
please, clarify return type

2023-04-04 10:31 UTC, anfimovdm commented on alws/test_scheduler.py
> +        repos.extend(flavor_repos)
can it be better, if we will iterate by new arrays and add them in `repos`?
like this
```python3
build_repositories = [...]
linked_build_repos = [...]
flavor_repos = [...]
for repo_arr in (
    build_repositories,
    linked_build_repos,
    flavor_repos,
):
    repos.extend(repo_arr)
```
it's up to you

2023-04-04 10:33 UTC, anfimovdm commented
also, could you please create unit test for this code?

2023-04-07 15:47 UTC, javihernandez commented
> also, could you please create unit test for this code?

Added unit tests for the newly introduced function and fixed review comments, ready again for another round of review

2023-04-12 10:08 UTC, anfimovdm approved these changes

2023-04-13 09:00 UTC, merged