Albs84
AlmaLinux/albs-web-server pull request #52
Opened 2021-12-09 13:26 UTC by monkrobot

Add repository ID to response from backend for release. Fixed communication with beholder service

2021-12-09 14:04 UTC, soksanichenko requested changes

2021-12-09 14:04 UTC, soksanichenko commented on alws/releases.py
> +    clean_ref_dist_name_lower = clean_ref_dist_name.lower()
Can var `clean_ref_dist_name` be None?

2021-12-09 14:04 UTC, soksanichenko commented on alws/releases.py
>      repo_name_regex = re.compile(r'\w+-\d-(?P<name>\w+(-\w+)?)')
Module `re` compiles and caches regexps inside itself, so you don't need do it. FYI

2021-12-09 14:04 UTC, soksanichenko commented on alws/utils/beholder_client.py
> +                json_ = await response.json()
bad name of the var. Some `json_dict` or `json_data` is better

2021-12-09 14:04 UTC, soksanichenko commented on alws/utils/beholder_client.py
>                  response.raise_for_status()
You should call `raise_for_status()` before reading any data. And I'm not sure that aiohttp has the same method

2021-12-09 14:41 UTC, anfimovdm requested changes

2021-12-09 14:41 UTC, anfimovdm commented on alws/releases.py
> +    oracle_response = await BeholderClient(settings.packages_oracle_host).post(
If you deleted OracleClient, so there doesn’t any sense to use packages_oracle_host, better to use var for beholder host

2021-12-09 17:16 UTC, soksanichenko requested changes

2021-12-09 17:16 UTC, soksanichenko commented on alws/utils/beholder_client.py
>                  response.raise_for_status()
https://docs.aiohttp.org/en/stable/client_reference.html, look at param `raise_for_status`

2021-12-10 08:19 UTC, anfimovdm approved these changes

2021-12-10 08:34 UTC, soksanichenko approved these changes

2021-12-10 11:16 UTC, merged