Replace CasWrapper on ImmudbWrapper
AlmaLinux/albs-web-server pull request #608
Opened 2023-08-02 18:51 UTC by anfimovdm

2023-08-03 08:44 UTC, maccelf approved these changes

2023-08-03 09:25 UTC, Korulag commented on docker-compose.yml
> +    image: codenotary/immudb:latest
I'd say we use some version (1.5.0 for example or 1.5-almalinux-8-minimal)

2023-08-08 08:20 UTC, zklevsha approved these changes

2023-08-08 09:05 UTC, zklevsha requested changes
fix is needed for compose:

`Service 'web_server' failed to build : Build failed`

2023-08-09 09:25 UTC, anfimovdm commented
> fix is needed for compose:
> 
> `Service 'web_server' failed to build : Build failed`

@zklevsha it's okay for now, tests are falling because [immudb-wrapper](https://github.com/AlmaLinux/immudb-wrapper) repo doesn't have `0.1.0` tag

2023-08-16 14:49 UTC, Korulag approved these changes

2023-08-16 15:51 UTC, merged