Updated README info
AlmaLinux/albs-web-server pull request #61
Opened 2021-12-22 10:11 UTC by sboldyreva

2021-12-22 10:46 UTC, Korulag requested changes

2021-12-22 10:46 UTC, Korulag commented on README.md
> +* PostgreSQL 13 - database
Duplicate of 15 line

2021-12-22 10:54 UTC, sboldyreva commented on README.md
> +* PostgreSQL 13 - database
Done

2021-12-23 14:00 UTC, Korulag approved these changes

2021-12-23 14:01 UTC, merged