Add test configuration field to build ref
AlmaLinux/albs-web-server pull request #630
Opened 2023-09-07 09:27 UTC by maccelf

2023-09-11 08:43 UTC, Korulag approved these changes

2023-09-11 12:57 UTC, anfimovdm requested changes
please fix failed tests

2023-09-13 08:28 UTC, anfimovdm approved these changes

2023-09-13 09:04 UTC, Korulag approved these changes

2023-09-14 15:58 UTC, merged