Fix creating new sign key
AlmaLinux/albs-web-server pull request #663
Opened 2023-10-18 11:53 UTC by Korulag

Fixed internal server error when creating new sign key if it already exists or when the platform from the payload is not on the database. https://github.com/AlmaLinux/build-system/issues/66

2023-10-19 08:10 UTC, anfimovdm requested changes

2023-10-19 08:10 UTC, anfimovdm commented on tests/fixtures/sign_keys.py
> +}
why do you use constant instead of fixture?

2023-10-19 08:10 UTC, anfimovdm commented on tests/fixtures/sign_keys.py
> +async def sign_key_with_platform(
unused fixture

2023-10-19 08:10 UTC, anfimovdm commented on tests/test_api/test_sign_keys.py
> +        print(response.text)
I think we can remove this print

2023-10-19 08:37 UTC, anfimovdm approved these changes

2023-11-02 14:38 UTC, zklevsha approved these changes

2023-11-08 11:26 UTC, merged