ALBS-1061: Fix "Restart build tests" functionality
AlmaLinux/albs-web-server pull request #711
Opened 2024-02-01 09:32 UTC by maccelf

After a "Restart build tests" action only affected tests should restart

Resolves: AlmaLinux/build-system#169

2024-02-01 14:56 UTC, zklevsha requested changes

2024-02-01 14:56 UTC, zklevsha commented on alws/crud/test.py
> +                failed = True
Maybe we should break out of loop after failed=True? I don`t see why we need to continue

2024-02-01 14:58 UTC, zklevsha requested changes

2024-02-01 14:58 UTC, zklevsha commented on alws/crud/test.py
> +                failed = True
Maybe we should break out of loop after failed=True? I don`t see why we need to continue

2024-02-01 15:13 UTC, javihernandez commented on alws/crud/test.py
> +        last_reviosion = build_task.test_tasks[-1].revision
typo `last_reviosion`, it should be `last_revision`

2024-02-02 12:48 UTC, zklevsha approved these changes

2024-02-13 10:12 UTC, Korulag approved these changes

2024-02-13 10:12 UTC, merged