Fix duplicates GitHub Issues
AlmaLinux/albs-web-server pull request #770
Opened 2024-04-01 17:58 UTC by maccelf

Fixes: AlmaLinux/build-system#241

2024-04-01 18:01 UTC, maccelf commented
Blocked by https://github.com/AlmaLinux/albs-github-integration/pull/4

2024-04-02 11:22 UTC, anfimovdm requested changes

2024-04-02 11:22 UTC, anfimovdm commented on alws/release_planner.py
>                          )
we can move the logic with the github integration into a separate function and reuse it in the `alws/release_planner.py` and `alws/crud/errata.py` modules

2024-04-03 06:40 UTC, soksanichenko requested changes

2024-04-03 06:40 UTC, soksanichenko commented on alws/crud/errata.py
> +    if settings.github_integration_enabled:
I think you can use. It looks better for me

```
if not settings.github_integration_enabled:
  return db_errata
<the rest code>
```

2024-04-03 11:19 UTC, Korulag approved these changes

2024-04-09 12:43 UTC, anfimovdm approved these changes

2024-04-09 12:44 UTC, merged