RBAC for Test Repositories - Issue #105
AlmaLinux/albs-web-server pull request #881
Opened 2024-06-27 16:39 UTC by amizhen

Resolves: https://github.com/AlmaLinux/build-system/issues/105
•Teams must now be assigned to Test Repositories upon creation
•Only members of a Test Repo's team can modify the Test Repo
•Done in conjunction with a pull request in frontend: https://github.com/amizhen/albs-frontend/tree/bs-105

2024-06-28 09:06 UTC, maccelf requested changes

2024-06-28 09:06 UTC, maccelf commented on alws/schemas/test_repository_schema.py
> +    owner_id: int
Related https://github.com/AlmaLinux/albs-frontend/pull/475/files#r1658387259

2024-06-28 15:10 UTC, maccelf approved these changes

2024-06-28 23:21 UTC, javihernandez approved these changes

2024-07-02 10:49 UTC, javihernandez commented on tests/fixtures/repositories.py
> +        'owner_id': 1,
Just spotted this before merging. `owner_id` is no longer required, can you please remove it?

2024-07-03 12:21 UTC, merged